Adds Option to Copy Panel to Clipboard
mihonapp/mihon pull request #1003
Opened 2024-07-11 08:34 UTC by Animeboynz

Uses Android's ClipboardManager to copy an Panel to the clipboard.

2024-07-11 08:48 UTC, Animeboynz commented
Damb you Build Checks.

2024-07-11 08:54 UTC, Animeboynz commented
Well finally down to one issue and its one I'm definitely not going to attempt as I'll probably break the entire thing xD

`/home/runner/work/mihon/mihon/app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderViewModel.kt:84:7: Class ReaderViewModel is too large. Consider splitting it into smaller pieces. [LargeClass]`

2024-07-12 09:51 UTC, Animeboynz commented
@AntsyLich This is basically done from my end, just let me know if you need me to remove the UI or if there is anything you need me to do

2024-07-24 13:08 UTC, AntsyLich commented
Rebase and fix build thanks

2024-07-25 15:46 UTC, AntsyLich requested changes
Also do a rebase instead of merging. It's a total mess

2024-07-25 15:46 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderViewModel.kt
> +    private fun handleImage(isCopy: Boolean) {
```suggestion
    fun shareImage(copy: Boolean) {
```

2024-07-25 15:49 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderViewModel.kt
> +    private fun handleImage(isCopy: Boolean) {
or
```kt
    fun shareImage(copyToClipboard: Boolean) {
```

2024-07-26 13:25 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
> +        val clipboardManager = applicationContext.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
will require an import
```suggestion
        val clipboardManager = applicationContext.getSystemService<ClipboardManager>()
```

2024-07-26 20:35 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
> +    }
```suggestion
    private fun onCopyImageResult(uri: Uri) {
        val clipboardManager = applicationContext.getSystemService<ClipboardManager>() ?: return
        val clipData = ClipData.newUri(applicationContext.contentResolver, "", uri)
        clipboardManager.setPrimaryClip(clipData)
    }
```

2024-07-26 21:00 UTC, merged