Add Copy Tracker URL on icon long press
mihonapp/mihon pull request #1101
Opened 2024-08-10 20:44 UTC by mm12

resolves #1087. 

When the icon for a tracker is held down, the tracker URL is copied to the clipboard, if it exists. 

From @BrutuZ's comment, I have also added it to the menu:
![image](https://github.com/user-attachments/assets/043285b1-ffb5-46fb-abd9-3ae1557478e5)

2024-08-10 21:09 UTC, BrutuZ commented
Re: https://github.com/mihonapp/mihon/issues/1087#issuecomment-2280654971, how about adding "Copy to clipboard" to the 3-dot menu too?

inb4 Antsy: Switch "Implements" for a [supported keyword](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue)

2024-08-10 22:00 UTC, AntsyLich commented
Replace text with "Copy link"?

2024-08-10 22:06 UTC, AntsyLich commented
Yeah do that

2024-08-10 22:46 UTC, AntsyLich requested changes

2024-08-10 22:46 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/track/components/TrackLogoIcon.kt
> +        onClick != null -> Modifier.clickableNoIndication(onClick = onClick)
You can pass in a null `onLongClick` value. So revert back to the previous if else and pass in `onLongClick` as is.

2024-08-10 22:46 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackInfoDialog.kt
> +    private fun copyTrackerLink(context: Context, trackItem: TrackItem) {
```suggestion
    private fun Context.copyTrackerLink(trackItem: TrackItem) {
```

2024-08-11 16:54 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/track/components/TrackLogoIcon.kt
> +        Modifier.clickableNoIndication(onLongClick = onLongClick, onClick = onClick)
```suggestion
        Modifier.clickableNoIndication(onClick = onClick, onLongClick = onLongClick)
```

2024-08-11 17:10 UTC, merged