Migrate tracking APIs to DTOs
mihonapp/mihon pull request #1103
Opened 2024-08-10 23:37 UTC by MajorTanya

Changes the handling of tracker API responses to be parsed to DTOs instead of doing so "manually" by use of `jsonPrimitive`s and/or `Json.decodeFromString` invocations.

This greatly simplifies the API response handling.

Renamed constants to SCREAMING_SNAKE_CASE.

Largely tried to name the DTOs in a uniform pattern, with the tracker's (short) name at the beginning of file and data class names (ALOAuth instead of OAuth, etc).

With these changes, no area of the code base should be using `jsonPrimitive` and/or `Json.decodeFromString` anymore.

2024-08-11 00:21 UTC, MajorTanya commented
Checked MAL, AL, Kitsu, MU, and Shikimori, they all seem to work just fine.

I don't have a Bangumi account nor do I have Komga/Kavita/Suwayomi set up (although I didn't touch those last three, they should be the same as before).

Bangumi needs checking whether it works correctly (searching, adding/deleting, updating progress, status, scores, dates). Should also check if Mihon can correctly fetch data from Bangumi when the user opens the tracking sheet by manually changing data on the website first and seeing if Mihon correctly updates when the tracking sheet is opened.

2024-08-11 09:06 UTC, MajorTanya commented
Seems like Kitsu is going up in flames right after I checked this approach works. Presumably their API will be the same even if they switch domains but for the time being, that's another blocker for the PR I'd wager.

2024-08-11 16:53 UTC, AntsyLich requested changes
Bangumi can be shortened to BGM

2024-08-11 16:53 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistUtils.kt
> +fun Track.toAnilistStatus() = when (status) {
```suggestion
fun Track.toApiStatus() = when (status) {
```

2024-08-11 16:53 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistUtils.kt
> +fun DomainTrack.toAnilistScore(): String = when (preferences.anilistScoreType().get()) {
```suggestion
fun DomainTrack.toApiScore(): String = when (preferences.anilistScoreType().get()) {
```

2024-08-11 16:53 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/BangumiUtils.kt
> +fun Track.toBangumiStatus() = when (status) {
```suggestion
fun Track.toApiStatus() = when (status) {
```

2024-08-11 16:53 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/KitsuUtils.kt
> +fun Track.toKitsuStatus() = when (status) {
```suggestion
fun Track.toApiStatus() = when (status) {
```

2024-08-11 16:53 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/KitsuUtils.kt
> +fun Track.toKitsuScore(): String? {
```suggestion
fun Track.toApiScore(): String? {
```

2024-08-19 06:05 UTC, MajorTanya commented
might be slightly blocked by #1130, depending on whether or not it happens

2024-08-27 06:10 UTC, NeKoOuO commented
@MajorTanya if you need a BGM account i can help you register one

2024-08-28 15:02 UTC, MajorTanya commented
Shikimori still crashes the app if a user tries to delete an entry from it when the remote entry doesn't exist anymore (user deleted it through other means like the website) due to an uncaught HttpException (404). This is unchanged to previous behaviour but should be addressed somehow.

2024-09-02 17:22 UTC, AntsyLich requested changes

2024-09-02 19:24 UTC, AntsyLich approved these changes

2024-09-02 19:46 UTC, merged