Allow Copying of Library List
mihonapp/mihon pull request #1161
Opened 2024-08-26 04:20 UTC by Animeboynz

Closes #43
| Image 1 | Image 2 |
| ------- | ------- |
| ![image](https://github.com/user-attachments/assets/ad57e51d-dbbb-46c8-bfca-8349740a6243) | ![image](https://github.com/user-attachments/assets/7de65abc-4621-41ef-8fc7-6ab9fab4e777) |

2024-08-26 05:03 UTC, AntsyLich commented
I'm more inclined towards share as csv instead of copy to clipboard

2024-08-26 05:36 UTC, Animeboynz commented
> I'm more inclined towards share as csv instead of copy to clipboard

Ill do that as soon as I have AS working again

2024-08-26 09:48 UTC, Animeboynz commented
Ignore the non localised strings and stuff for now, Ill fix that once the code itself is approved.
Should probably add a notification or toast too now that I think about it.

2025-02-23 18:19 UTC, AntsyLich requested changes
And changelog

2025-02-23 18:19 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/export/LibraryExporter.kt
> +    }
```suggestion
    private val escapeRequired = listOf("\r", "\n", "\"", ",")

    private fun generateCsvData(favorites: List<Manga>, options: ExportOptions): String {
        val rows = buildList(favorites.size) {
            favorites.forEach { manga ->
                add(buildList(options.columnSize) {
                    if (options.includeTitle) add(manga.title)
                    if (options.includeAuthor) add(manga.author)
                    if (options.includeArtist) add(manga.artist)
                })
            }
        }

        return rows.joinToString("\n") { columns ->
            columns.joinToString(",") columns@{ column ->
                if (column.isNullOrBlank()) return@columns ""

                if (escapeRequired.any { column.contains(it) }) {
                    column.replace("\"", "\"\"").let { "\"$it\"" }
                } else {
                    column
                }
            }
        }
    }
```

2025-02-24 11:16 UTC, Animeboynz commented
and here too

2025-02-24 16:19 UTC, AntsyLich requested changes
Also where my co-author smh

2025-02-24 16:19 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/export/LibraryExporter.kt
> +    fun exportToCsv(
Do `scope.launch` from UI side
```suggestion
    suspend fun exportToCsv(
```

2025-02-24 16:19 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/export/LibraryExporter.kt
> +        ).count { it }
```suggestion
        )
            .count { it }
```

2025-02-24 16:19 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/export/LibraryExporter.kt
> +                )
```suggestion
                buildList(columnSize) {
                    if (options.includeTitle) add(manga.title)
                    if (options.includeAuthor) add(manga.author)
                    if (options.includeArtist) add(manga.artist)
                }
                    .let(::add)
```

2025-02-24 16:19 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDataScreen.kt
> +
```suggestion
```

2025-02-24 16:19 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDataScreen.kt
> +        var favoritesState by remember { mutableStateOf<List<Manga>>(emptyList()) }
```suggestion
        val scope = rememberCoroutineScope()
        val getFavorites = remember { Injekt.get<GetFavorites>() }
        var favorites by remember { mutableStateOf<List<Manga>>(emptyList()) }
```

2025-02-24 16:19 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDataScreen.kt
> +                exportToCsv(
```suggestion
                LibraryExporter.exportToCsv(
```

2025-02-24 16:19 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDataScreen.kt
> +        isArtistSelected: Boolean,
Just pass the whole `ExportOptions` and also return it

2025-02-25 10:41 UTC, AntsyLich requested changes

2025-02-25 10:41 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/export/LibraryExporter.kt
> +        return rows.joinToString("\n") { columns ->
https://datatracker.ietf.org/doc/html/rfc4180#section-2
```suggestion
        return rows.joinToString("\r\n") { columns ->
```

2025-02-25 10:41 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/export/LibraryExporter.kt
> +            }
```suggestion
            }
            onExportComplete()
```

2025-02-25 10:41 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDataScreen.kt
> +                    ) {
```suggestion
                    Row(verticalAlignment = Alignment.CenterVertically) {
```

2025-02-25 10:41 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDataScreen.kt
> +                    ) {
```suggestion
                    Row(verticalAlignment = Alignment.CenterVertically) {
```

2025-02-25 10:41 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDataScreen.kt
> +                    ) {
```suggestion
                    Row(verticalAlignment = Alignment.CenterVertically) {
```

2025-02-25 10:41 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDataScreen.kt
> +                    saveFileLauncher.launch("library_list.csv")
```suggestion
                    saveFileLauncher.launch("mihon_library.csv")
```

2025-02-25 10:41 UTC, AntsyLich commented on CHANGELOG.md
> +- Added option to export library to a CSV file ([@Animeboynz](https://github.com/Animeboynz), [@AntsyLich](https://github.com/AntsyLich)) ([#1161](https://github.com/mihonapp/mihon/pull/1161))
```suggestion
- Add option to export minimal library information to a CSV file ([@Animeboynz](https://github.com/Animeboynz), [@AntsyLich](https://github.com/AntsyLich)) ([#1161](https://github.com/mihonapp/mihon/pull/1161))
```

2025-02-26 04:31 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDataScreen.kt
> +        currentOptions: ExportOptions,
Should be the first parameter

2025-02-26 05:04 UTC, AntsyLich approved these changes

2025-02-26 05:09 UTC, merged