Add advanced Library setting to allow library manga's titles to update from source
mihonapp/mihon pull request #1182
Opened 2024-09-01 00:47 UTC by FlaminSarge

This adds a setting under Advanced > Library to allow any entry, not just favorites, to update their titles from source.
It attempts to move the downloaded files as well by renaming the entry's download folder. It does not currently attempt to move downloaded files into an existing folder (if another title exists/conflicts).

### Images
| Image 1 | Image 2 |
| ------- | ------- |
|  <img width="270" alt="Screenshot 2024-08-31 at 5 35 21 PM" src="https://github.com/user-attachments/assets/0dd88c7f-9abd-4aa8-8ec7-59a7f9559b6e"> |  <img width="279" alt="Screenshot 2024-08-31 at 5 35 53 PM" src="https://github.com/user-attachments/assets/2b98146b-e0b0-4511-bf61-168bfd18f8af"> |

2024-09-01 00:48 UTC, FlaminSarge commented
I was considering putting this under the "Automatically update metadata" setting under Library settings; unsure whether it should go there or under Advanced, given how it's a slightly more dangerous setting when it comes to Download handling.

I need advice on better download handling for this PR before I move it out of draft, as while a simple rename works for some cases, it doesn't handle the edge case of existing folder nor do I do any cache handling yet.

2024-10-12 03:46 UTC, AntsyLich commented on i18n/README.md
> +Original English strings are managed in `src/commonMain/moko-resources/base/`. Translations are done externally via Weblate. See [our website](https://mihon.app/docs/contribute#translation) for more
Separate PR

2025-03-06 16:22 UTC, cuong-tran commented on app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadManager.kt
> +    fun renameManga(source: Source, manga: Manga, newTitle: String) {
What will happen with `downloading` entries, all those `_tmp` files?

2025-03-11 01:00 UTC, FlaminSarge commented
Needs cache handling before this can be merged; right now, if a manga gets renamed in this way, the download cache doesn't know about it and the cache still thinks the old manga has the downloads, not the new one.

2025-03-11 02:06 UTC, cuong-tran commented
Time to migrate to use something like `hash(url)` as a preceeding of folder name, that should address various other issues.

2025-03-24 08:19 UTC, FlaminSarge commented on app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadManager.kt
> +    fun renameManga(source: Source, manga: Manga, newTitle: String) {
The user gets "an unknown error occured" and has to retry the download.

The exception is:
```Failed to createFile
    java.lang.IllegalArgumentException: Failed to determine if primary:Tachi/downloads/MangaDex (EN)/pants/Puzzle Kings_Ch.54_tmp is child of primary:Tachi: java.io.FileNotFoundException: Missing file for primary:Tachi/downloads/MangaDex (EN)/pants/Puzzle Kings_Ch.54_tmp at /storage/emulated/0/Tachi/downloads/MangaDex (EN)/pants/Puzzle Kings_Ch.54_tmp
    	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
    	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
    	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
    	at android.content.ContentResolver.call(ContentResolver.java:2450)
    	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1380)
    	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:56)
    	at com.hippo.unifile.TreeDocumentFile.createFile(TreeDocumentFile.java:86)
    	at eu.kanade.tachiyomi.data.download.Downloader$downloadImage$2.invokeSuspend(Downloader.kt:478)
    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)```

2025-03-24 08:34 UTC, FlaminSarge commented on app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadManager.kt
> +    fun renameManga(source: Source, manga: Manga, newTitle: String) {
I've made it so that a manga gets removed from queue if it's getting renamed; this will handle both the new case of in-library manga as well as the existing case of non-library manga that are being downloaded when the name change happens.

2025-05-06 16:59 UTC, AntsyLich requested changes

2025-05-06 16:59 UTC, AntsyLich commented on CHANGELOG.md
> +- Add advanced Library setting to allow library manga's titles to update from source ([@FlaminSarge](https://github.com/FlaminSarge)) ([#1182](https://github.com/mihonapp/mihon/pull/1182))
```suggestion
- Add advance option to always update manga title from source ([@FlaminSarge](https://github.com/FlaminSarge)) ([#1182](https://github.com/mihonapp/mihon/pull/1182))
```

2025-05-06 16:59 UTC, AntsyLich commented on app/src/main/java/eu/kanade/domain/manga/interactor/UpdateManga.kt
> +        source: Source,
You don't need to pass the source here. The manga object has the source id use that to get the source instance in download manager

2025-05-06 16:59 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadManager.kt
> +        downloader.removeFromQueue(manga)
The should be part of the toggle summary as a warning

2025-05-06 16:59 UTC, AntsyLich commented on app/src/main/java/eu/kanade/domain/manga/interactor/UpdateManga.kt
> +        val localTitle = localManga.title
inline it

2025-05-06 16:59 UTC, AntsyLich commented on i18n/src/commonMain/moko-resources/base/strings.xml
> +    <string name="pref_update_library_manga_titles">Allow title changes for library entries</string>
```suggestion
    <string name="pref_update_library_manga_titles">Allow updating title for library entries</string>
```

2025-05-06 16:59 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadCache.kt
> +            }
I've kinda forgotten how the `UniFile` internal works but if you make a new folder with the manga's old name do the downloads still work?

2025-05-06 21:28 UTC, FlaminSarge commented on app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadCache.kt
> +            }
On my device it looks like if you try to rename a folder to an existing folder, the one getting renamed gets a "(2)" at the end or something similar. I could try to reuse the folder if it exists, maybe, and move the files into it, but I'm slightly conerned it'll result in orphaned cbz's with (2) at the end.

2025-05-07 01:56 UTC, FlaminSarge commented on app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadCache.kt
> +            }
Thanks to ```                sourceDir.mangaDirs -= oldMangaDirName
```
I don't believe those will stick around.
Are you concerned about hanging `MangaDirectory` obj references?

2025-05-07 21:12 UTC, AntsyLich requested changes

2025-05-07 21:12 UTC, AntsyLich commented on CHANGELOG.md
> +- Add advanced option to always update manga title from source ([@FlaminSarge](https://github.com/FlaminSarge)) ([#1182](https://github.com/mihonapp/mihon/pull/1182))
```suggestion
- Add advance option to always update manga title from source ([@FlaminSarge](https://github.com/FlaminSarge)) ([#1182](https://github.com/mihonapp/mihon/pull/1182))
```

2025-05-07 21:12 UTC, AntsyLich commented on i18n/src/commonMain/moko-resources/base/strings.xml
> +    <string name="pref_update_library_manga_titles_summary">If a source has a different title for an entry than the one stored in the library, update it to match the source\'s title.\nWarning: if a m
```suggestion
    <string name="pref_update_library_manga_titles">Update library manga titles to match source</string>
    <string name="pref_update_library_manga_titles_summary">Warning: if a manga is renamed, it will be removed from the download queue (if present).</string>
```

2025-05-07 21:12 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadManager.kt
> +        downloader.removeFromQueue(manga)
Honestly should be added back afterwards

2025-05-07 23:23 UTC, FlaminSarge commented on app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadManager.kt
> +        downloader.removeFromQueue(manga)
I don't think the DB MangaRepository.update call is guaranteed to be done by the time this happens, so that ends up being pretty messy, I think.

2025-05-08 01:18 UTC, Soitora commented on CHANGELOG.md
> +- Add advanced option to always update manga title from source ([@FlaminSarge](https://github.com/FlaminSarge)) ([#1182](https://github.com/mihonapp/mihon/pull/1182))
Don't do this, Advance is the wrong word to use...

2025-05-08 22:08 UTC, AntsyLich approved these changes

2025-05-08 22:09 UTC, merged