update all trackers progress when new tracker is added
mihonapp/mihon pull request #1372
Opened 2024-10-25 02:41 UTC by cuong-tran

Whenever a new tracker is add, it will try to sync all trackers together with local reading progress

2024-10-25 22:22 UTC, AntsyLich commented
what's the reasoning?

2024-10-26 04:18 UTC, cuong-tran commented
for example, if user has 2 trackers but with different progress, when user adds the 2nd tracker with a higher progress, this will sync all trackers to that higher progress instead of waiting for the next sync.

Also, there is the TODO put right there state that.

2025-02-23 17:26 UTC, AntsyLich requested changes
Apply the suggestion to the rest of the changes and add changelog

2025-02-23 17:26 UTC, AntsyLich commented on app/src/main/java/eu/kanade/domain/track/interactor/AddTracks.kt
> +            val context = Injekt.get<Application>()
Move to constructor

2025-02-23 17:26 UTC, AntsyLich commented on app/src/main/java/eu/kanade/domain/track/interactor/AddTracks.kt
> +                .forEach { (track, e) ->
```suggestion
                .forEach { (track, e) ->
                    if (track == null) return@forEach
```

2025-02-23 17:26 UTC, AntsyLich commented on app/src/main/java/eu/kanade/domain/track/interactor/AddTracks.kt
> +                        )
```suggestion
                        context.toast(context.stringResource(MR.strings.track_error, track.name, e.message ?: ""))
```

2025-02-23 18:20 UTC, BrutuZ commented
Will it prompt the user? It should, there's the snackbar from "Update on manually mark as read" already, so could call that

2025-03-25 19:21 UTC, cuong-tran commented
This is wrong. Closing.

2025-03-25 19:21 UTC, closed without merging