Add Hikka Tracker Integration
mihonapp/mihon pull request #1386
Opened 2024-10-26 23:31 UTC by Lorg0n

Add Hikka tracker integration

Add support for Hikka (https://hikka.io/), a Ukrainian online encyclopedia for manga and etc.

Changes implemented:
- Added new Hikka tracker with ID 10
- Implemented OAuth authentication flow with auto token refresh
- Added full sync support for:
  - Reading status (Reading, Completed, On Hold, etc.)
  - Chapter progress
  - Scores (0-10 scale)
  - Manga search and linking
- Created necessary data models and API integration
- Added UI elements for tracker settings

All changes have been tested:
- [x] Authentication flow
- [x] Manga search and linking
- [x] Status/progress syncing
- [x] Error handling

### Images
| Settings Screen | Manga Track Dialog |
| ------- | ------- |
| ![image](https://github.com/user-attachments/assets/c86d3109-7834-4428-906b-0e5497717ee9) | ![image](https://github.com/user-attachments/assets/c5dc020a-68ec-4ddf-ac66-bace0ac60b58) |

2024-10-26 23:34 UTC, Smol-Ame commented
Include "Closes #1145" in your PR description to link to the feature request issue

2024-10-26 23:38 UTC, AntsyLich commented
How does the auth flow work for this site?

2024-10-26 23:44 UTC, Lorg0n commented
> How does the auth flow work for this site?

I didn't mean anything special, just standard OAuth authorization.

2024-10-26 23:50 UTC, AntsyLich commented
Ok I was ambiguous. How does one create a oauth client or get the reference?

2024-10-26 23:54 UTC, Lorg0n commented
> Ладно, я был двусмысленным. Как создать клиент oauth или получить ссылку?

https://hikka.io/settings/applications

2024-10-27 04:58 UTC, AntsyLich commented
Trying to create a new client I'm getting the error "Invalid field endpoint in request body"

2024-10-27 05:00 UTC, AntsyLich commented
Ok so the issue is with using the custom redirect url

2024-10-27 13:43 UTC, AntsyLich commented
Blocked by https://github.com/hikka-io/hikka/pull/347

2024-10-27 14:30 UTC, Lorg0n commented
I'll redo the authorisation to work after the changes then

2024-10-27 17:10 UTC, Lorg0n commented
Okay, I changed the authorization. My local tests went fine
![image](https://github.com/user-attachments/assets/815dea53-8402-4f42-95db-0725b95f5df6)

2024-10-27 21:31 UTC, Lorg0n commented
I don't understand why the test fails, even though everything is fine in my fork. I didn't touch MangaScreenModel.kt at all

2024-10-27 21:32 UTC, AntsyLich commented
Yeah ignore that bit. It passes lint previously but suddenly started to flag from today.

2025-02-23 07:23 UTC, AntsyLich commented
Rebase please

2025-02-25 21:10 UTC, MajorTanya requested changes
These are some code things I found, going to play around with the actual integration for a bit now.

2025-02-25 21:39 UTC, MajorTanya commented
I just saw that [Hikka merged support for start and end dates](https://github.com/hikka-io/hikka/pull/362) for manga. If you could add that once it's running in production it would be really cool. If I understand their code correctly, this is about starting and ending dates for the title itself, not the user's starting and ending dates of reading, so this would be used in the search like other trackers do.

2025-02-26 18:00 UTC, Lorg0n commented on app/src/main/java/eu/kanade/tachiyomi/data/track/hikka/HikkaApi.kt
> +                )
Unfortunately, hikka doesn't have the ability to sort by best match. In theory you can leave this field just empty, but then in the query for example for `naru` in the first item in general unknown manga with a rating of 0.

2025-02-26 18:06 UTC, Lorg0n commented
Unfortunately [this update](https://github.com/hikka-io/hikka/pull/362) only applies to a request for information about a specific manga and does not give that data in a search query

2025-02-26 18:13 UTC, Lorg0n commented on app/src/main/java/eu/kanade/tachiyomi/data/track/hikka/HikkaApi.kt
> +        private const val SCOPE = "readlist,read:user-details"
Yes, "readlist" is the **read** AND **update** permission for the read manga.

2025-02-26 18:27 UTC, Lorg0n commented on app/src/main/java/eu/kanade/tachiyomi/data/track/hikka/Hikka.kt
> +    }
Kind of not. At least companion object is at the bottom only in `Bangumi`. In the others, it's on top everywhere else (`MyAnimeList`, `Shikimori`, `MangaUpdates`, etc.).

2025-02-26 18:45 UTC, MajorTanya commented on app/src/main/java/eu/kanade/tachiyomi/data/track/hikka/Hikka.kt
> +    }
Oh, lol. Guess I got too much Bangumi on my brain after my recent firestorm of Bangumi PRs. Ignore and carry on.

2025-02-26 19:10 UTC, Lorg0n commented on app/src/main/java/eu/kanade/tachiyomi/data/track/hikka/HikkaApi.kt
> +                )
Oh, I didn't realise what question you were asking me. I understand, yes, I guess I forgot to change it to standard during debugging

2025-02-27 09:16 UTC, AntsyLich commented
Merge in the latest change from main

2025-02-27 15:35 UTC, MajorTanya requested changes
Can't find anything breaking or broken, and the code appears to be nice too. Thanks for the good work.

2025-02-27 15:35 UTC, MajorTanya commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsTrackingScreen.kt
> +                        title = trackerManager.hikka.name,
This doesn't compile. Remove the `title` line and it should be good.

2025-02-27 15:38 UTC, MajorTanya commented
Somehow messed up with hiding the comment, it is not outdated. Please take a look at the requested change.

2025-02-27 15:46 UTC, MajorTanya commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsTrackingScreen.kt
> +                        title = trackerManager.hikka.name,
And in case you're worried, it still shows Hikka in the Tracking screen.

2025-02-27 16:57 UTC, Lorg0n commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsTrackingScreen.kt
> +                        title = trackerManager.hikka.name,
> And in case you're worried, it still shows Hikka in the Tracking screen.

Yes, thanks, the problem appeared because I wrote back when all trackers had a title. Fixed it now

2025-02-27 17:02 UTC, MajorTanya approved these changes
I think this time for real I can't find anything broken. It appeared to work once the change in b34745342ab550470e53f84184d232b4fcb45009 was applied. Didn't do super in-depth edge case testing but cursory adding, moving, scoring, etc all seemed to work. 👍

2025-02-27 19:36 UTC, AntsyLich approved these changes

2025-02-27 19:38 UTC, AntsyLich commented
The PR as is fine but I'll delay merging this until a small DB rework so we won't require workarounds like this
![image](https://github.com/user-attachments/assets/6a967631-f59e-4ed5-8181-500a73bffc8a)

Estimating a week at max

2025-02-27 19:51 UTC, Lorg0n commented
I'll ask the Hikka developers about a unique number(id) for the manga, I think I'll solve the problem

2025-02-27 19:52 UTC, AntsyLich commented
In case you misunderstood this is something I intent to fix Mihon side since more tracker we add in the future may not have numeric ID

2025-02-27 19:55 UTC, Lorg0n commented
Okay, I got it

2025-03-06 08:43 UTC, AntsyLich commented
You might want to include the new stuff from #1810

2025-03-06 23:35 UTC, Lorg0n commented
Add `start date` and `type` of content. Unfortunately, a search of the Hikka site doesn't yield any additional data to add here.
![image](https://github.com/user-attachments/assets/8e7b0ebc-f6d6-45cd-a017-3a5d28a60761)

2025-03-06 23:37 UTC, MajorTanya commented
> Add `start date` and `type` of content. Unfortunately, a search of the Hikka site doesn't yield any additional data to add here. ![image](https://private-user-images.githubusercontent.com/37798530/420126493-8e7b0ebc-f6d6-45cd-a017-3a5d28a60761.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEzMDQ0NjUsIm5iZiI6MTc0MTMwNDE2NSwicGF0aCI6Ii8zNzc5ODUzMC80MjAxMjY0OTMtOGU3YjBlYmMtZjZkNi00NWNkLWEwMTctM2E1ZDI4YTYwNzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzA2VDIzMzYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxYzBjYTYyZTc4NjY0NmZmMTljNDNmNjQzOTUwZjkxOTliZmZiMjc1OTBhNmU0NzhjODhhMWQ4ZmY3ZTIzZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sgiKppROQrBi2ChBhtESpPjjy1yhG1oV2NNjc3W1Ors)

tragic but thanks 👍

2025-03-16 23:54 UTC, Lorg0n commented
> The PR as is fine but I'll delay merging this until a small DB rework so we won't require workarounds like this ![image](https://private-user-images.githubusercontent.com/59261191/417758904-6a967631-f59e-4ed5-8181-500a73bffc8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDIxNjkzODgsIm5iZiI6MTc0MjE2OTA4OCwicGF0aCI6Ii81OTI2MTE5MS80MTc3NTg5MDQtNmE5Njc2MzEtZjU5ZS00ZWQ1LTgxODEtNTAwYTczYmZmYzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzE2VDIzNTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNTg3YzVkMzQyYTM5NzZmZDMzZWQ1YjFlNWQ5NjZmNzU2M2JlMjc5MjllMzFkNjlhOTI2OTIyOWY5MjM0MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.haFpnYXahAFf-_soIw3JpsHrjEieAhIflK2_91Yde4Y)
> 
> Estimating a week at max

Any news on this so far?

2025-05-01 08:54 UTC, prem-k-r commented on app/src/main/java/eu/kanade/tachiyomi/data/track/hikka/Hikka.kt
> +    override fun getLogo(): Int = R.drawable.ic_tracker_hikka
Rest of the trackers' logos are in the `drawable-nodpi` folder. Maybe move this one there too for consistency.

2025-05-01 09:41 UTC, Lorg0n commented on app/src/main/java/eu/kanade/tachiyomi/data/track/hikka/Hikka.kt
> +    override fun getLogo(): Int = R.drawable.ic_tracker_hikka
Yeah, it's strange. In Android Studio, the two folders appear as one folder

2025-05-01 21:51 UTC, Lorg0n commented on app/src/main/java/eu/kanade/tachiyomi/data/track/hikka/Hikka.kt
> +    override fun getLogo(): Int = R.drawable.ic_tracker_hikka
Thanks, I'm new to Android Studio

2025-12-10 09:16 UTC, AntsyLich commented
@Lorg0n I'm extremely sorry for still not merging this PR. I've slowly started working on the tracker and database changes I wanted to do so this should hopefully be merged by the end of the year (given either you or I redo the logic based on new tracker interface)

2026-01-19 16:54 UTC, Teashrock commented
Just found this website myself, and decided I'd be good to request a tracker. And I see that this pull request already is. How's it going?

2026-04-27 15:47 UTC, Zeddy-Coder commented
Hope 0.20 will finally merge this pr

2026-07-06 18:21 UTC, AntsyLich requested changes

2026-07-06 18:21 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/track/hikka/HikkaApi.kt
> +            "hiOeTH2BaDf77ZcA9W5Z"
```suggestion
        private const val CLIENT_REFERENCE = "598ef1f5-b9d2-4e66-8b65-06949d5e14fc"
        private const val CLIENT_SECRET = "OKwzrNOZxq40psFgfcCUYddnvaeZWDnd34rt7fdcB5GmHoBBQuNTWX" +
            "61sZs8KECEWVXtMUDtq8QC4t9WX4DwWWYLXEVlgnlUXGT1fWCb-18c" +
            "Zd2m8Co-8HN6JQcjoP-B"
```

2026-07-06 21:10 UTC, AntsyLich approved these changes

2026-07-06 21:18 UTC, merged

2026-07-06 21:21 UTC, volbil commented
Just for info new client for Mihon is marked as verified on hikka.io now

2026-07-07 09:24 UTC, AntsyLich commented
@Lorg0n thanks for the work and sorry it took so long ❤️

2026-07-07 11:57 UTC, Lorg0n commented
> @Lorg0n thanks for the work and sorry it took so long ❤️ 

❤️

2026-07-08 13:15 UTC, MajorTanya commented on app/src/main/java/eu/kanade/tachiyomi/data/track/hikka/HikkaInterceptor.kt
> +            setAuth(HKOAuth(currAuth.accessToken, authTokenInfo.expiration, authTokenInfo.created))
@Lorg0n I noticed this when I tried to debug an unclosed response issue somewhere in this, and I apologize for only bringing this up now, post-merge, but what exactly are these two requests doing? You never use the first one for anything other than checking whether it was successful. And the second one is just closed if it's unsuccessful, but afaik, the interceptor will continue its work?

Is this a "check if the refresh token is still alive" + "get a new access token" situation? If so, why is the first request content unused?

2026-07-08 14:35 UTC, Lorg0n commented on app/src/main/java/eu/kanade/tachiyomi/data/track/hikka/HikkaInterceptor.kt
> +            setAuth(HKOAuth(currAuth.accessToken, authTokenInfo.expiration, authTokenInfo.created))
Hikka API has a quirk where /auth/token/info doesn't extend the token's lifetime (at least when I wrote this). To refresh it, the code has to hit any other endpoint outside /auth/, so /user/me is just the easiest one to use. The data isn't needed since the request itself is just to verify if the token is alive and automatically extend it.

And about the second request continuing after failing, that was probably just an oversight while writing and debugging. I must have missed it since it never actually crashed for me during testing

2026-07-08 14:39 UTC, MajorTanya commented on app/src/main/java/eu/kanade/tachiyomi/data/track/hikka/HikkaInterceptor.kt
> +            setAuth(HKOAuth(currAuth.accessToken, authTokenInfo.expiration, authTokenInfo.created))
> Hikka API has a quirk where /auth/token/info doesn't extend the token's lifetime (at least when I wrote this). To refresh it, the code has to hit any other endpoint outside /auth/, so /user/me is just the easiest one to use.

I see, understandable then.

> And about the second request continuing after failing, that was probably just an oversight while writing and debugging. I must have missed it since it never actually crashed for me during testing

I'm actually not sure which of these requests is the one not being closed properly since it's stubbornly refusing to happen reliably or in any reproducible manner now that I've added some logcats locally...
All I've seen is an error in the search results saying that an unclosed response exists and that OKHttp couldn't do anything further until it was closed. I'm not even sure if it's the interceptor doing this or something else somewhere, though the rest of the code looks to me like it always uses the response body via `parseAs` or `use`, so those should be closed every time and this is the place with manually closed responses and only in certain conditions.

Maybe I'm just stumbling across a race condition when Hikka is a bit slow to respond or something, I don't know.

2026-07-08 14:54 UTC, Lorg0n commented on app/src/main/java/eu/kanade/tachiyomi/data/track/hikka/HikkaInterceptor.kt
> +            setAuth(HKOAuth(currAuth.accessToken, authTokenInfo.expiration, authTokenInfo.created))
Maybe the leak happens because the first request (/user/me) is never closed when it's successful? It skips the if and stays open. The second one is also just missing a throw on failure

2026-07-08 14:58 UTC, MajorTanya commented on app/src/main/java/eu/kanade/tachiyomi/data/track/hikka/HikkaInterceptor.kt
> +            setAuth(HKOAuth(currAuth.accessToken, authTokenInfo.expiration, authTokenInfo.created))
> Maybe the leak happens because the first request (/user/me) is never closed when it's successful? It skips the if and stays open. The second one is also just missing a throw on failure

That was my initial thought too, but I replaced the isExpired check to always be true, and it doesn't happen basically ever, even though this code path must be hit on every interaction I have with Hikka (I added dozens of titles to provoke this).

I did the always true thing because the token expires a month later but I had it happen at least three times in my build before I even started to investigate it, so it can't be about the token directly? It's all very confusing but maybe I'm missing something obvious.

2026-07-08 15:18 UTC, Lorg0n commented on app/src/main/java/eu/kanade/tachiyomi/data/track/hikka/HikkaInterceptor.kt
> +            setAuth(HKOAuth(currAuth.accessToken, authTokenInfo.expiration, authTokenInfo.created))
Maybe the leak actually happens in HikkaApi.kt inside getRead()? When the app checks if a title is on the list and gets a 404 (meaning it's not there yet), it returns null, but the response is never closed. That explains why adding a bunch of new titles triggered the unclosed response errors for you

2026-07-08 15:20 UTC, MajorTanya commented on app/src/main/java/eu/kanade/tachiyomi/data/track/hikka/HikkaInterceptor.kt
> +            setAuth(HKOAuth(currAuth.accessToken, authTokenInfo.expiration, authTokenInfo.created))
> Maybe the leak actually happens in HikkaApi.kt inside getRead()? When the app checks if a title is on the list and gets a 404 (meaning it's not there yet), it returns null, but the response is never closed. That explains why adding a bunch of new titles triggered the unclosed response errors for you

You misunderstood, adding all those titles _didn't_ trigger it like, ever. Whenever it did happen, it was always upon opening the Hikka search on a library entry that didn't have a Hikka entry set yet.

2026-07-08 15:22 UTC, MajorTanya commented on app/src/main/java/eu/kanade/tachiyomi/data/track/hikka/HikkaInterceptor.kt
> +            setAuth(HKOAuth(currAuth.accessToken, authTokenInfo.expiration, authTokenInfo.created))
I'll open an issue about this so we can stop bothering the 8 participants in this with emails ...