Drag reorder category
mihonapp/mihon pull request #1427
Opened 2024-10-31 19:14 UTC by cuong-tran

Drag & Drop to reorder category quickly

2024-11-07 14:55 UTC, AntsyLich requested changes
Also where demo video

2024-11-07 14:55 UTC, AntsyLich commented on domain/src/main/java/tachiyomi/domain/category/interactor/ReorderCategory.kt
> +    suspend fun await(category: Category, offset: Int) = withNonCancellableContext {
```suggestion
    suspend fun changeOrder(category: Category, newOrder: Int) = withNonCancellableContext {
```

2024-11-07 14:55 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/category/CategoryScreenModel.kt
> +    fun moveTo(category: Category, offset: Int) {
```suggestion
    fun changeOrder(category: Category, newOrder: Int) {
```

2024-11-07 14:55 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/category/CategoryScreen.kt
> +            moveTo = screenModel::moveTo,
```suggestion
            changeOrder = screenModel::changeOrder,
```

2024-11-07 14:55 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/category/components/CategoryListItem.kt
> +            }
```suggestion
            Icon(
                imageVector = Icons.Outlined.DragHandle, 
                contentDescription = null,
                modifier = Modifier
                    .padding(16.dp)
                    .draggableHandle(),
            )
```

2024-11-07 14:55 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/category/components/CategoryListItem.kt
> +                .padding(MaterialTheme.padding.small),
```suggestion
                .padding(vertical = MaterialTheme.padding.small)
                .padding(
                    start = MaterialTheme.padding.small,
                    end = MaterialTheme.padding.medium,
                ),
```

2024-11-07 14:55 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/category/components/CategoryListItem.kt
> +                    .padding(start = MaterialTheme.padding.small),
```suggestion
                    .weight(1f),
```

2024-11-07 14:55 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/category/CategoryScreen.kt
> +fun Category.key() = "category-$id"
```suggestion
private val Category.key get() = "category-$id"
```

2024-11-07 14:55 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/category/CategoryScreen.kt
> +    moveTo: (Category, Int) -> Unit,
```suggestion
    changeOrder: (Category, Int) -> Unit,
```

2024-11-07 14:55 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/category/CategoryScreen.kt
> +            moveTo = moveTo,
```suggestion
            changeOrder = changeOrder,
```

2024-11-07 14:55 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/category/CategoryScreen.kt
> +    moveTo: (Category, Int) -> Unit,
```suggestion
    changeOrder: (Category, Int) -> Unit,
```

2024-11-07 16:56 UTC, cuong-tran commented
> Also where demo video

Video uploaded.

2024-11-07 18:01 UTC, Animeboynz commented
Just personal opinion, even though the functionality is cool, I prefer the old look of categories. Everything isn't centre aligned like that one.
![Screenshot_20241108_065922_TachiyomiSY](https://github.com/user-attachments/assets/b348c264-a3a4-4c24-91ae-6cd4e934f1e5)

2024-11-22 09:01 UTC, AntsyLich commented
Remove card from the category

2024-11-22 14:24 UTC, cuong-tran commented
> Remove card from the category

sorry I don't get what do you mean?

2024-11-27 13:50 UTC, AntsyLich commented
`CategoryListItem` has `ElevatedCard` I'm asking for you to remove it

2024-11-28 07:55 UTC, cuong-tran commented
> `CategoryListItem` has `ElevatedCard` I'm asking for you to remove it

What style do you prefer? Flat without card style?

Remove Card would look like this:
![image](https://github.com/user-attachments/assets/1753345e-5600-4606-a5a0-6ba0cdc5a6a5)

2024-12-25 12:31 UTC, Dinkarkumar commented
Hello  @AntsyLich , Is this still in progress ?

2024-12-26 02:17 UTC, cuong-tran commented
> > `CategoryListItem` has `ElevatedCard` I'm asking for you to remove it
> 
> What style do you prefer? Flat without card style?
> 
> Remove Card would look like this:
> ![image](https://github.com/user-attachments/assets/1753345e-5600-4606-a5a0-6ba0cdc5a6a5)
> 

I'm waiting for Antsy response

2025-02-23 17:17 UTC, AntsyLich reviewed
Changelog

2025-02-25 18:41 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/category/CategoryScreen.kt
> +    }
What's the point of this?

2025-02-25 19:16 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/category/CategoryScreen.kt
> +    }
Figured it out

2025-02-26 05:29 UTC, AntsyLich approved these changes

2025-02-26 05:37 UTC, merged