Allow disabling reader's zoom out (#62)
mihonapp/mihon pull request #302
Opened 2024-01-31 14:34 UTC by Splintorien

Closes #62

2024-02-14 12:31 UTC, AntsyLich commented
Make it a button to disable zoom out

2024-02-14 18:07 UTC, AntsyLich commented
Current implementation: Enable (on by default)
I want: Disable (off by default)

2024-02-14 18:36 UTC, AntsyLich commented
Umm

2024-02-14 18:42 UTC, Splintorien commented
> Umm

I wanted updated my fork but it did some weird things, all good

2024-02-14 18:50 UTC, AntsyLich commented
Next time make cha

2024-02-14 18:50 UTC, AntsyLich commented
Oops

2024-02-16 11:58 UTC, AntsyLich requested changes

2024-02-16 11:58 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/reader/settings/GeneralSettingsPage.kt
> +    )
Should be in [ReadingModePage.kt](https://github.com/mihonapp/mihon/blob/6bdb37be65757ca903c5c2a249ca03331b04d673/app/src/main/java/eu/kanade/presentation/reader/settings/ReadingModePage.kt) under `WebtoonViewerSettings`

2024-02-16 11:58 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/setting/ReaderPreferences.kt
> +    fun disableZoomOut() = preferenceStore.getBoolean("disable_zoom_out", false)
```suggestion
    fun webtoonDisableZoomOut() = preferenceStore.getBoolean("webtoon_disable_zoom_out", false)
```

2024-02-16 11:58 UTC, AntsyLich commented on i18n/src/commonMain/resources/MR/base/strings.xml
> +    <string name="pref_disable_zoom_out">Disable zoom out</string>
```suggestion
    <string name="pref_webtoon_disable_zoom_out">Disable zoom out</string>
```

2024-02-16 11:58 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonRecyclerView.kt
> +            }
Only invoke this if `currentScale` is less than `DEFAUT_RATE`

2024-02-16 12:42 UTC, AntsyLich requested changes

2024-02-16 12:42 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonRecyclerView.kt
> +            if (currentScale < DEFAULT_RATE) {
```suggestion
            if (value && currentScale < DEFAULT_RATE) {
```

2024-02-16 12:42 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/reader/settings/ReadingModePage.kt
> +
```suggestion
```

2024-02-16 12:42 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsReaderScreen.kt
> +                )
```suggestion
                ),
```

2024-02-24 19:40 UTC, merged