feat: add cross device sync
mihonapp/mihon pull request #40
Opened 2024-01-16 17:02 UTC by KaiserBh

ref: [GitHub - Tachiyomi Pull Request #9790](https://github.com/tachiyomiorg/tachiyomi/pull/9790)

Currently, there are two services available: [Syncyomi](https://github.com/SyncYomi/SyncYomi), which is self-hosted, and Google Drive.

Once merged you will need to create OAuth 2.0 Client IDs in google console then replace the `app/src/main/assets/client_secrets.json`

![image](https://github.com/jobobby04/TachiyomiSY/assets/41852205/23518863-9974-4e29-994d-9de8fd0f4477)

Once all of that is done just need to set the app to `publish` instead of `testing` that way everyone can access it otherwise limited to 100 users we add for testing, we don't need to submit the app for approval since we are not using sensitive scopes. More info [here](https://support.google.com/cloud/answer/13463073?authuser=1&visit_id=638407747036157208-1875300124&rd=1)

### OAuth Consent Screen
![image](https://github.com/jobobby04/TachiyomiSY/assets/41852205/bc96cc6a-8420-4f86-9a96-8a6cc2d22289)

### Scopes
![image](https://github.com/jobobby04/TachiyomiSY/assets/41852205/0f0ba3f6-d2f3-4a56-a4eb-6c84fdd2c580)

![image](https://github.com/jobobby04/TachiyomiSY/assets/41852205/a3c36b7b-80d7-4c09-91da-59a13f267581)
![image](https://github.com/jobobby04/TachiyomiSY/assets/41852205/477072dd-dcd4-4898-9efd-0c9a17a87c1f)
![image](https://github.com/jobobby04/TachiyomiSY/assets/41852205/5fc146b8-eb9a-4228-90fb-4fd6d0194a78)
![image](https://github.com/jobobby04/TachiyomiSY/assets/41852205/46713ac7-38fe-4853-b071-c50b574f1380)
![image](https://github.com/jobobby04/TachiyomiSY/assets/41852205/4fdf68f4-2577-416a-9c98-d6bbf3421c00)

2024-01-17 10:36 UTC, AntsyLich commented
Initially I'll do reviews on small independent sections and ask you to make separate pr for them e.g. the db change you did which you can go ahead and make a pr for

2024-01-18 04:31 UTC, KaiserBh commented
> Initially I'll do reviews on small independent sections and ask you to make separate pr for them e.g. the db change you did which you can go ahead and make a pr for

#113

2024-01-19 11:27 UTC, AntsyLich requested changes
Make a separate PR for this file and also maybe prefix all of them with `__SYNC__`?

2024-01-19 11:27 UTC, AntsyLich commented on domain/src/main/java/tachiyomi/domain/sync/SyncPreferences.kt
> +    }
why not use an enum?

2024-01-19 11:27 UTC, AntsyLich commented on domain/src/main/java/tachiyomi/domain/sync/SyncPreferences.kt
> +)
Move into separate `model` package. Rename to `SyncSettings`?

2024-01-19 11:27 UTC, AntsyLich commented on domain/src/main/java/tachiyomi/domain/sync/SyncPreferences.kt
> +    fun syncAPIKey() = preferenceStore.getString("sync_api_key", "")
```suggestion
    fun clientHost() = preferenceStore.getString("sync_client_host", "127.0.0.1:69420")
    fun clientAPIKey() = preferenceStore.getString("sync_client_api_key", "")
```

2024-01-19 11:27 UTC, AntsyLich commented on domain/src/main/java/tachiyomi/domain/sync/SyncPreferences.kt
> +    fun syncFlags() = preferenceStore.getInt("sync_flags", Flags.Defaults)
```suggestion
    fun autoSyncAfter() = preferenceStore.getInt("auto_sync_after", Flags.Never)
```

2024-01-20 06:49 UTC, KaiserBh commented
> Make a separate PR for this file and also maybe prefix all of them with `__SYNC__`?

#149 Let me know on that branch if I need to change anything else.

2024-02-03 13:43 UTC, LightDestory commented
Build fails?

2024-02-05 03:23 UTC, KaiserBh commented
> Build fails?

Hmm the build is okay it's just detekt errors, which is just too strict at the moment, to name a few:

`Class 'SyncPreferences' with '13' functions detected. Defined threshold inside classes is set to '11' [TooManyFunctions]`

`/home/runner/work/mihon/mihon/app/src/main/java/eu/kanade/tachiyomi/data/sync/SyncManager.kt:371:43: This expression contains a magic number. Consider defining it to a well named constant. [MagicNumber]`

`/home/runner/work/mihon/mihon/app/src/main/java/eu/kanade/tachiyomi/data/sync/SyncManager.kt:372:44: This expression contains a magic number. Consider defining it to a well named constant. [MagicNumber]`

2024-02-24 10:03 UTC, closed without merging