Made some changes to ComicInfo metadata
mihonapp/mihon pull request #459
Opened 2024-02-28 10:26 UTC by Shamicen

I made some changes to `ComicInfo` metadata generation:

The `web field` had a schema change and can now contain multiple space separated reference website links. Therefore ComicInfo metadata will from now on include the `source URL` and all available `tracker URLs`.
For more information look at this issue https://github.com/anansi-project/comicinfo/issues/56 and this PR https://github.com/anansi-project/comicinfo/pull/57

I changed the `translator field` to use the source name if no `scanlator` name is available.

2024-02-28 10:33 UTC, AntsyLich commented
> I changed the `translator field` to use the source name if no `scanlator` name is available.

Not sure i like that change

2024-02-28 11:10 UTC, Shamicen commented
I was planning to make it so that `LocalSource` chapters will appear with their metadata in the future. 

As of now we would be unable to display a scanlator for most sources, because a lot of them don't populate the scanlator field with their name if they are also the scanlators.

Their are also a few aggregator sources that already "incorrectly" populate the scanlator field with their source name.

For use inside `Mihon` the field will only show up in `LocalSource` and even if the source wasn't the original scanlator seeing which source the manga is from looks better / gives the user more information then just leaving it blank. 

We could make it standard policy for sources that are also scanlators to populate the scanlator field with their source name and for sources that aren't to not populate it, if we don't want to risk "wrong" translator names. Whether or not the 3rd party extension will actually follow it is a different question but it can't hurt to try.

We could alternatively create another non schema field and use this for our `LocalSource` when no scanlator is available.

Tell me what you think and I'll make the necessary changes.

2024-02-28 13:00 UTC, AntsyLich commented
Could do a custom field then for source and in local source do `scanlator ?: mihon_source`

2024-02-28 14:12 UTC, Shamicen commented
> Could do a custom field then for source

I implemented it

2024-02-28 14:26 UTC, AntsyLich requested changes

2024-02-28 14:26 UTC, AntsyLich commented on core-metadata/src/main/java/tachiyomi/core/metadata/comicinfo/ComicInfo.kt
> +    @XmlSerialName("SourceMihon", "http://www.w3.org/2001/XMLSchema", "ty")
```suggestion
    @XmlSerialName("SourceMihon", "http://www.w3.org/2001/XMLSchema", "mh")
```

2024-02-28 14:26 UTC, AntsyLich commented on app/src/main/java/eu/kanade/domain/manga/model/Manga.kt
> +    urls: String,
```suggestion
    urls: List<String>,
```

2024-02-28 14:26 UTC, AntsyLich commented on app/src/main/java/eu/kanade/domain/manga/model/Manga.kt
> +    web = ComicInfo.Web(urls),
```suggestion
    web = ComicInfo.Web(urls.joinToString(" ")),
```

2024-02-28 14:26 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +            .trim()
```suggestion
        val urls = getTracks.await(manga.id)
            .mapNotNull { track ->
                track.remoteUrl.takeUnless { url -> url.isBlank() }?.trim()
             }
            .plus(source.getChapterUrl(chapter.toSChapter()).trim())
            .distinct()
```

2024-02-29 08:16 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +             }
```suggestion
            }
```

2024-02-29 17:57 UTC, merged