Added configuration options to e-ink page flashes
mihonapp/mihon pull request #625
Opened 2024-04-06 02:16 UTC by sirlag

Adds some configuration options for the e-ink page flash to better support a variety of devices. 

Added Flash duration options - 100-1500ms
Added Flash style options - Black, White, White/Black
Added Flash spacing options - 1 - 10 pages

The current page flash system really is a hack over the reader (adding a colored rectangle over the reader for the duration of the flash) hooked into every page. Trying to use this hook to enable and disable the invert filter had low success, particularly because it only triggers after the page change animation has already started to play. Attempt to add a proper invert or inline screen clear will probably require a refactor for on-exit hooks that can delay a transition, but that seemed beyond the scope of getting this more usable for our e-ink users.

| Disabled | Enabled |
| ------- | ------- |
| ![image](https://github.com/mihonapp/mihon/assets/1882979/9a0af454-0238-4366-ba5b-b4b5f8a2875b) | ![image](https://github.com/mihonapp/mihon/assets/1882979/3b036e08-2b0f-4c24-b388-8e66c83c8998) |

Closes #585

2024-04-06 02:34 UTC, AntsyLich requested changes
Make all strings into string resource. And add the settings in reader settings sheet

2024-04-06 02:34 UTC, AntsyLich commented on i18n/src/commonMain/resources/MR/base/strings.xml
> +    <string name="pref_flash_spacing">Pages Between Flashes</string>
```suggestion
    <string name="pref_flash_page_interval">Flash every</string>
```

2024-04-06 02:34 UTC, AntsyLich commented on i18n/src/commonMain/resources/MR/base/strings.xml
> +    <string name="pref_flash_style">Style of Page Flash</string>
```suggestion
    <string name="pref_flash_with">Flash with</string>
```

2024-04-06 02:34 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/setting/ReaderPreferences.kt
> +        BOTH
```suggestion
        WHITE_BLACK
```

2024-04-06 02:34 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/setting/ReaderPreferences.kt
> +    enum class FlashMode {
```suggestion
    enum class FlashColor {
```

2024-04-06 02:34 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/setting/ReaderPreferences.kt
> +    fun flashMode() = preferenceStore.getEnum("pref_reader_flash_mode", FlashMode.BLACK)
```suggestion
    fun flashDurationMillis() = preferenceStore.getInt("pref_reader_flash_duration", 100)

    fun flashPageInterval() = preferenceStore.getInt("pref_reader_flash_interval", 1)

    fun flashColor() = preferenceStore.getEnum("pref_reader_flash_mode", FlashMode.BLACK)
```

2024-04-06 02:34 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsReaderScreen.kt
> +                        ReaderPreferences.FlashMode.BOTH to "Both",
```suggestion
                        ReaderPreferences.FlashMode.WHITE_BLACK to "White and Black",
```

2024-04-11 14:06 UTC, sirlag commented
> As far as I can tell all requested changes have been made!

There is one outstanding issue that is being discussed, where the state management for the flash interval is currently loaded in a non-reactive way, and thus does not update when set in the reader quick settings sheet

2024-04-11 19:23 UTC, mainrs commented
Before this gets merged I'd like to bring up something I just discovered.

My Ebook offers a SDK that can be used to properly flash the screen similar to the procedure Kindle devices do.

Would it be possible to somehow abstract the flashing logic using an interface? And mihon could then inject different implementations depending on which device it runs on. 

https://github.com/artatechsoft/InkbookSDK

2024-04-11 19:40 UTC, sirlag commented
> My Ebook offers a SDK...

Seems interesting. At a glance, it does appear to be designed for pre-compose android development, so I am not 100% sure how well their refresh hook would work with compose. 

As mentioned in the initial PR Comment, trying to get this properly supported with the way the current reader is implemented will be a lot more work, think of this PR as a bandage to help out e-ink users, without needing substantial changes at this time.

2024-06-26 20:04 UTC, merged